IMGLINK = ./projects/footprint/assets/thumbnail.png
VIDLINK = ./projects/footprint/assets/thumbnail.mp4
WORKTITLE = footprint
GITHUBLINK = https://github.com/Frikallo/footprint
DESCRIPTIONEN = A python OSINT tool to discover and analyze the digital footprint of a targets email or username across millions of sites.
DESCRIPTIONFR = Un outil OSINT en python pour découvrir et analyser l'empreinte numérique d'un courriel ou d'un nom d'utilisateur cible sur des millions de sites.
NAMEOFLINKEN = Github
NAMEOFLINKFR = Github
REPO = autotweets
ARCHIVED = False
INDEVELOPMENT = False
EXPERIMENTAL = False
LINK2 = pypi.org/project/footprint-py/
LINK2TITLEEN = Download
LINK2TITLEEN = Télécharger