baseURL = "https://aetherai.xyz/"
languageName = "English"
languageCode = "en-us"
title = "AetherAI"
theme = ["eai-base","eai-www"]
contentDir = "content"
publishDir = "public"
googleAnalytics = "G-4SDKJXT0HF"
[params]
    env = "production"
    logo_image_url=""
    meta_image=""
    contact_mail="contact@aether.ai"
    site_type="website"
    sitename = "AetherAI"
    [params.organization]
        name="AetherAI"
        baseURL="https://aetherai.xyz/"
        description="A decentralized grassroots collective of volunteer researchers, engineers, and developers focused on AI alignment, scaling, and open source AI research."
        email="contact@aether.ai"
        sameAs=["https://github.com/Frikallo","https://wandb.ai/aetherai","https://huggingface.co/AetherAI"]
        foundingDate="2022-03-24"
        logo="https://eleuther.ai/images/promo.png"
    [params.homeInfoParams]
        Title="AetherAI"
        Content="A grassroots collective of researchers working to open source AI research."
    [[params.socialIcons]]
        name="discord"
        url="https://discord.gg/7VkE3Kuyqf"
    [[params.socialIcons]]
        name="github"
        url="https://github.com/Frikallo"
    [params.label]
        icon = "/images/libre.svg"
        iconHeight = "48"
    [params.assets]
        disableHLJS = true
        favicon="favicon.ico"
        favicon16x16="favicon/favicon-16x16.png"
        favicon32x32="favicon/favicon-32x32.png"
        apple_touch_icon="favicon/apple-touch-icon.png"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
  category = "categories"
  tags = "tags"
  domain = "domain"
  deliverable = "deliverables"
  status = "status"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 5