baseURL = "https://frikallo.github.io/blog/"
languageName = "English"
languageCode = "en-us"
title = "AetherAI Blog"
theme = ["eai-base","eai-blog"]
contentDir = "content-blog"
publishDir="public-blog"
googleAnalytics = "G-9KCLV8BK53"
[params]
    env = "production"
    [params.organization]
        name="AetherAI"
        baseURL="https://frikallo.github.io/"
        description="A decentralized grassroots collective of volunteer researchers, engineers, and developers focused on AI alignment, scaling, and open source AI research."
        email="contact@aether.ai"
        sameAs="https://github.com/AetherAI"
        foundingDate="2020-07-02"
        logo="https://eleuther.ai/images/promo.png"
    ShowAllPagesInArchive = true
    [params.label]
        icon = "/images/libre.svg"
        iconHeight = "48px"
    [params.assets]
        disableHLJS = true
        favicon="favicon.ico"
        favicon16x16="favicon/favicon-16x16.png"
        favicon32x32="favicon/favicon-32x32.png"
        apple_touch_icon="favicon/apple-touch-icon.png"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
  category = "categories"
  tags = "tags"
[menu]
  [[menu.main]]
    name = "Home"
    url = "https://frikallo.github.io/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "https://frikallo.github.io/about/"
    weight = 2
  [[menu.main]]
    name = "FAQ"
    url = "https://frikallo.github.io/faq/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 4
  [[menu.main]]
    name = "Publications"
    url = "https://frikallo.github.io/publications/"
    weight = 5