IMGLINK = ./projects/autotweets/assets/thumbnail.png
VIDLINK = ./projects/autotweets/assets/thumbnail.mp4
WORKTITLE = AutoTweets
GITHUBLINK = https://github.com/Frikallo/autotweets
DESCRIPTIONEN = HuggingTweets on wheels. A CLI program to automatically generate Tweets with Huggingface
DESCRIPTIONFR = HuggingTweets sur roues. Un programme CLI pour générer automatiquement des Tweets avec Huggingface
NAMEOFLINKEN = Github
NAMEOFLINKFR = Github
REPO = autotweets
ARCHIVED = False
INDEVELOPMENT = False
EXPERIMENTAL = False
LINK2 = None
LINK2TITLEEN = 
LINK2TITLEEN = 