IMGLINK = https://github.com/Frikallo/frikallo.github.io/blob/main/projects/MISST/assets/thumbnail.png
VIDLINK = https://github.com/Frikallo/frikallo.github.io/blob/main/projects/MISST/assets/thumbnail.mp4
WORKTITLE = MISST
GITHUBLINK = https://github.com/Frikallo/MISST
DESCRIPTIONEN = A local GUI music source separation tool built on Tkinter and public Facebook models serving as a free and open source Stem Player
DESCRIPTIONFR = Un outil de séparation des sources musicales à interface graphique locale construit sur Tkinter et des modèles Facebook publics servant de lecteur Stem gratuit et à code source ouvert.
NAMEOFLINKEN = Github
NAMEOFLINKFR = Github
REPO = misst
ARCHIVED = False
INDEVELOPMENT = True
EXPERIMENTAL = False
LINK2 = https://github.com/Frikallo/MISST/releases/latest
LINK2TITLEEN = Download
LINK2TITLEEN = Télécharger